version: 2

seeds:
    - name: raw_titanic
      description: "The survivorship dataset we'll use to train our ML model"

    - name: predict_me
      description: "Fake individuals not seen in our training data we will be prediciting survivorship for"

models:
  - name: data_train
    description: "The subset of data used to train our machine learning model"
    
  - name: data_test
    description: "The subset of data used to test our machine learning model performance"

  - name: features
    descriptions: "The features we want to use to train and test our machine learning model"
